# Generated by Django 5.2.17 on 2026-10-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True)),
                ('url_path', models.CharField(max_length=200, unique=True)),
                ('meta_title', models.CharField(max_length=60)),
                ('meta_description', models.CharField(max_length=160)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots', models.CharField(default='index, follow', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
