# Generated by Django 5.2.17 on 2026-10-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_seopage"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="location",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="price_range",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="location",
            name="website_url",
            field=models.URLField(blank=True),
        ),
    ]
